repos:
# - repo: https://github.com/pre-commit/mirrors-prettier
#   # rev: ''  # Use the sha / tag you want to point at
#   hooks:
#   - id: prettier
#     additional_dependencies:
#     - prettier@2.1.2
#     - '@prettier/plugin-xml@0.12.0'
#     types_or: [python]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-merge-conflict

# - repo: https://github.com/PyCQA/bandit
#   rev: 1.7.5  # Use the desired version of Bandit
#   hooks:
#     - id: bandit

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0  # Use the desired version of Bandit
  hooks:
    - id: isort

# - repo: https://github.com/PyCQA/pylint
#   rev: v2.17.5  # Use the desired version of Pylint
#   hooks:
#     - id: pylint

# - repo: https://github.com/PyCQA/flake8
#   rev: 6.1.0  # Use the desired version of Pylint
#   hooks:
#     - id: flake8

- repo: https://github.com/commitizen-tools/commitizen
  rev: 3.5.2
  hooks:
  - id: commitizen
    name: Check conventional commit message
    stages: [commit-msg]
